
name: mlo              # you should be able to change it
                       # just pay attention when pasting commands
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11        # developed w/ 3.11
  - pip                # pip
  - poetry             # poetry

platforms:
  - linux-64
